accepted = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "BSL-1.0",
    "CC0-1.0",
    "OFL-1.1",
    "Unicode-3.0",
    "Ubuntu-font-1.0",
    "AGPL-3.0-only",
    "AGPL-3.0-or-later",
]
