[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg",
    "getrandom_backend=\"wasm_js\"",
    "-C",
    "target-feature=+simd128",
]
runner = "/home/jeremyg/.cargo/bin/wasm-server-runner"

[doc.extern-map.regular]
bevy = "https://docs.rs/bevy/latest/"
egui = "https://docs.rs/egui/latest/"
